#ifndef _SSTL__SSTL_VERSION_INCLUDED
#define _SSTL__SSTL_VERSION_INCLUDED

#define SSTL_VERSION_MAJOR 0
#define SSTL_VERSION_MINOR 1

#define SSTL_VERSION_BINARY ((SSTL_VERSION_MAJOR) << 24) | (SSTL_VERSION_MINOR) << 16))
#define SSTL_VERSION_STRING SSTL_MACRO_STRING(SSTL_MACRO_CONCATENATE2(SSTL_VERSION_MAJOR,SSTL_VERSION_MINOR))
#define SSTL_FILE_VERSION   SSTL_VERSION_MAJOR,SSTL_VERSION_MINOR,0,0

#define SSTL_MACRO_STRING(x) #x
#define SSTL_MACRO_CONCATENATE(p1, p2) _SSTL_PRIVATE_MACRO_CONCATENATE(p1, p2)

#define SSTL_MACRO_CONCATENATE2(p1, p2)             _SSTL_PRIVATE_MACRO_CONCATENATE(p1, p2)
#define SSTL_MACRO_CONCATENATE3(p1, p2, p3)         SSTL_MACRO_CONCATENATE2(SSTL_MACRO_CONCATENATE2(p1, p2), p3)
#define SSTL_MACRO_CONCATENATE4(p1, p2, p3, p4)     SSTL_MACRO_CONCATENATE2(SSTL_MACRO_CONCATENATE3(p1, p2, p3), p4)
#define SSTL_MACRO_CONCATENATE5(p1, p2, p3, p4, p5) SSTL_MACRO_CONCATENATE2(SSTL_MACRO_CONCATENATE4(p1, p2, p3, p4), p5)

// Private

#define _SSTL_PRIVATE_MACRO_CONCATENATE_EXTRA(a, b) a##b
#define _SSTL_PRIVATE_MACRO_CONCATENATE(a, b) _SSTL_PRIVATE_MACRO_CONCATENATE_EXTRA(a, b)

#endif
